export const ORDER_ARTISTS_SUCCESS = 'ORDER_ARTISTS_SUCCESS';
export const ORDER_ARTISTS_ERROR = 'ORDER_ARTISTS_ERROR';
export const ORDER_ARTISTS_REQUEST = 'ORDER_ARTISTS_REQUEST';

export const ORDER_ALBUMS_SUCCESS = 'ORDER_ALBUMS_SUCCESS';
export const ORDER_ALBUMS_ERROR  = 'ORDER_ALBUMS_ERROR';
export const ORDER_ALBUMS_REQUEST = 'ORDER_ALBUMS_REQUEST';

export const ORDER_TRACKS_SUCCESS = 'ORDER_TRACKS_SUCCESS';
export const ORDER_TRACKS_ERROR  = 'ORDER_TRACKS_ERROR';
export const ORDER_TRACKS_REQUEST = 'ORDER_TRACKS_REQUEST';

export const ORDER_ARTIST = 'ORDER_ARTIST';
export const ORDER_ALBUM = 'ORDER_ALBUM';